### ISSUE TITLE
deploy 時に、lambda の AWS KMS エラー が発生する

### ISSUE THREAD

**Issue by halsk** [codeforjapan/remote-patient-monitoring-api#41]
[DEVELOPMENT.md](https://github.com/codeforjapan/remote-patient-monitoring-api/blob/develop/docs/DEVELOPMENT.md#6-run-test) に書きましたが、deploy 時にAPIがうまく動作しないケースがあります。

* lambda function の KMS まわりがエラーになる
* ~~API Gateway から lambda を実行する権限がなくなる~~ (解決済み)

という2つのエラーがありますが、原因が不明です。AWS に詳しい方、どなたか調査いただけると助かります🙏。

**Comment by halsk** [comment]
どこかでスペルミスしているだけな気がしてきた

**Comment by kenichisak** [comment]
初めまして。実際に動かして確認してないので見当違いでしたらすみません。

KMS の方についてですが下記の記事を見つけました。

https://dev.classmethod.jp/articles/kmsaccessdeniedexception-occurred-in-aws-lambda/

今回どのようなエラーが発生しているのか分からず書いていて恐縮ですが、この記事の`結論（原因の推測とワークアラウンド）`に書かれている通りだとしたら `redeploy-all` で stack を一度 remove してしまうと一時的に発生してしまうのではないでしょうか？

**Comment by halsk** [comment]
@kenichisak ありがとうございます！
こちらでは独自KMSは使っていないのですが、エラーの原因と対処方法は似ていますね。

* IAMロールの名称（物理名）を変更する
* IAMロールの識別子がAWSシステム内で切り替わるまで待つ

という解決策が示されていますが、ロールを変更するのは微妙・・・
結局今の解決策は、KMSを設定し直すという今の方法が解放になってしまいますね。

また、`API Gateway から lambda を実行する権限がなくなる` という不具合とは無関係な気もします。

**Comment by ghost** [comment]
はじめまして。
誤解でしたら大変恐縮です。

> API Gateway から lambda を実行する権限がなくなる

上記の原因ですが下記の設定ファイルに `remote-patient-monitoring-postAdminLogin-${self:provider.stage}` 
のLambdaパーミッションの記述が不足しているからではないでしょうか。

https://github.com/codeforjapan/remote-patient-monitoring-api/blob/develop/templates/api-gateway.yml

例えば、以下のような定義が必要そうに見受けられます。
```
  postAdminLoginApiPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: "remote-patient-monitoring-postAdminLogin-${self:provider.stage}"
      Action: "lambda:InvokeFunction"
      Principal: "apigateway.amazonaws.com"
```

ただ発生頻度がランダムであったり、定義済みのものでも起きるということであれば
異なる要因の可能性が高いかもしれません。
